<script setup>
  import sfx from "../assets/hello.mp3"
  const audio = new Audio(sfx) 
  function playHelloAudio(){
    audio.play()
  }

</script>

<template>
<v-container class="d-block bg-grey-lighten-4 rounded-sm">
  <h1 class="mb-2 text-h5"> Get word definitions </h1>
  <br/>
  <p><strong>Usage :</strong> The basic syntax of a URL request to the API is shown below:</p>
  <p class="text-cyan-accent-4 ma-2">
    https://en.dictionary-api.com/v1/{word}
  </p>
  <br/>
  <p>
    As an example, to get definition of English word hello, you can send request to
  </p>
  <p class="text-cyan-accent-4 ma-2">
    https://en.dictionary-api.com/v1/hello
  </p>
  <br/>
  <v-container class="d-block bg-grey-darken-3 rounded-sm">
     <pre class="wordblock">

[
  {
    "word": "hello",

    "definitions": [
      {
        "pos": "noun",
        "definition": "a greeting or expression of goodwill or acknowledgment",
        "cefr": "A2",
        "example": "As Mary entered the room, everyone turned to her and said, 'Hello!'"
      }
    ],
    
    "phonic": "/heˈloʊ/", 
    "audio": "https://storage.googleapis.com/dictionary_api_audio_files/src/hello.mp3", <v-btn @click="playHelloAudio" variant="tonal"><v-icon class="fas fa-volume-high"></v-icon></v-btn>

    "paragraph": "When greeting someone or starting a conversation, it is common to use the word hello. Hello is a friendly and polite way to acknowledge someone's presence or to initiate interaction. It is a versatile word that can be used in both formal and informal settings. Additionally, hello can also be used as an exclamation to express surprise or to get someone's attention. 
    For example, if you witness something unexpected, you might say Hello! Did you see that? or if you want to get someone's attention, you may say Hello! Can I ask you a question? 
    Overall, hello is a versatile word that is commonly used as a greeting, a way to initiate conversation, or as an exclamation to express surprise or gain attention."

  }
]

  </pre>
    </v-container>
    <br/>
    <br/>
    <v-spacer/>
    <hr/>
    <br/>
  <h2 class="text-h5">Important Note</h2>
    GPT Dictionary API contains 66589 words, with words definitions and a paragraph explains the word.<br/>
    All definition including part of speech, CEFR (The Common European Framework of Reference for Languages) for the word level, and an example for it. <br/>
    <br/>
    <strong>Caution</strong><br/> 
    CEFR level is inferenced by a specific trained GPT model, not an absolute correct answer.<br/>
    All content is generated by GPT model, including paragraph, definitions of a word. <br/>
    Although all content is double checked and validated, we can't guarantee all content is 100% correct.<br/>
  
  <br/>
    <br/>
    <v-spacer/>
    <hr/>
    <br/>

  <h2 class="text-h5">Donate</h2><br/>
  <p>GPT Dictionary API is—and always will be—free. <br/>

    Your donation directly helps the development of GPT Dictionary API and keeps the server running.</p>
    <br/>
    <a href="https://www.buymeacoffee.com/lenny0929" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/arial-yellow.png" alt="Buy Me A Coffee" style="height: 60px !important;width: 217px !important;" ></a>
      
    <br/>
    <br/>
    <v-spacer/>
    <hr/>
    <br/>

    <h2 class="text-h5">Downloads</h2><br/>
    <p>You can purchase and download all the files used in the GPT Dictionary API.<br/>
      
      Total GPT Dictionary contains 66589 words, with English words definitions and a paragraph explains the word.
      <br/><br/>  
      Easy to import to any database and simple to use. 
    </p>
    <br/>
    <v-btn href="https://www.buymeacoffee.com/lenny0929/extras" variant="outlined"> Check out Downloads </v-btn>
  
  </v-container>

</template>

<style>
.wordblock {
  word-break: normal;
  white-space: pre-wrap;
}


</style>